### ISSUE TITLE
Bug: qoibench shows wrong 'size kb' totals

### ISSUE THREAD

**Issue by M-Gonzalo** [wx257osn2/qoixx#10]
```
## Benchmarking ./vlcSnaps/*.png -- 10 runs

## Total for "./vlcSnaps"
        decode ms   encode ms   decode mpps   encode mpps   size kb    rate
qoi:       5.5211      7.1469       159.510       123.226       820   31.8%
qoixx:     4.5902      5.3635       191.860       164.198       820   31.8%
```
vlcSnaps is a folder of 58.045.051 bytes of optimized pngs. the qoi converted files for that are 109.163.275 bytes total.

**Comment by wx257osn2** [comment]
@M-Gonzalo 

1. Where is the `vlcSnaps` ? I don't know where the dataset is, so can't reproduce your result.
2. Do you means that `109.163.275` bytes as total of encoded qoi doesn't match  as 820 KiB ?
    - If true, it may not be wrong because the `size kb` shows the **average** of encoded qoi.

**Comment by M-Gonzalo** [comment]
> @M-Gonzalo
> 
>     1. Where is the `vlcSnaps` ? I don't know where the dataset is, so can't reproduce your result.
> 
>     2. Do you means that `109.163.275` bytes as total of encoded qoi doesn't match  as 820 KiB ?
>        
>        * If true, it may not be wrong because the `size kb` shows [the **average** of encoded qoi](https://github.com/wx257osn2/qoixx/blob/ef734e0d21fc34d148e4a24b1b4e5d72a0f26e5d/src/qoibench.cpp#L120).

Oooooh that explains it. It's an average, not a total. Yes, in that context, 820 KiB makes perfect sense. Sorry for the misunderstanding.
vlcSnaps is just a folder with screenshots, nothing particular about it.
