### ISSUE TITLE
ans1 entropy coder

### ISSUE THREAD

**Issue by M-Gonzalo** [wx257osn2/qoixx#9]
[As stated here](https://encode.su/threads/3753-QOI-(Quite-OK-Image-format)-lossless-image-compression-to-PNG-size?p=75219&viewfull=1#post75219), there is a very real possibility of turning qoi into a strong replacement for png. Coupled with a very fast ANS1 entropy coder, its ratio it's on par with heavily optimized png files that costs 2 orders of magnitude more to encode.

Would you like to look at that as an option for qoixx or perhaps a derivative program?

![image](https://user-images.githubusercontent.com/23223606/179212535-bfbed9a2-1834-45a8-88e5-cfc437b411b1.png)

**Comment by M-Gonzalo** [comment]
Here is a bash function to test it out:

```sh
qoi.ans1() {
    fp=$(pwd)/$1
    SECONDS=0
    BYTES="$(tam $1)"

    pushd $fp >/dev/null
    find . -type d | xargs -I{} mkdir -p "../$1-qoa/{}" \
    && find . -type f -print0 | du -sB1 --files0-from=- | sort -nr | cut -f2 \
    | parallel --bar "qoiconv {} $fp-qoa/{.}.qoi && kanzi -c -i $fp-qoa/{.}.qoi -o $fp-qoa/{.}.qoa -v 0 -t none -f -e ans1 && rm $fp-qoa/{.}.qoi"
    popd >/dev/null
    
    duration=$SECONDS
    echo $((($BYTES/1000000)/($duration))) mbps, $(calc 100*$(tam $1-qoa)/$BYTES) \%
}
```
Sample output:
```sh
$ qoi.ans1 $(pwd)/Imágenes-0 Imágenes-0
100% 297:0=0s ./Capturas/img.png                                                                                                                                                                       
397592 kbps, 20.89 %

```

**Comment by wx257osn2** [comment]
@M-Gonzalo  I read the thread of the forum. That sounds interesting.

> Would you like to look at that as an option for qoixx or perhaps a derivative program?

Thanks to choose the qoixx as qoi implementation.  
However, qoixx is intended to be a _fastest_ implementation with sufficient functinoality to replace [the reference implementation of qoi](https://github.com/phoboslab/qoi/) (and currently qoixx is fastest one on x86_64 as far as I know).
So, even if practical, implementing entropy coding on qoixx would be seemed excessive for me from what qoixx aims.  
Fortunately qoixx is the OSS under MIT, so you can implement the derivative program using qoixx as the qoi implementation.  
I find such efforts interesting, and when you find any suggestions for improvement of qoixx in your efforts, please report them here.

**Comment by M-Gonzalo** [comment]
> @M-Gonzalo I read the thread of the forum. That sounds interesting.
> 
> > Would you like to look at that as an option for qoixx or perhaps a derivative program?
> 
> Thanks to choose the qoixx as qoi implementation. However, qoixx is intended to be a _fastest_ implementation with sufficient functinoality to replace [the reference implementation of qoi](https://github.com/phoboslab/qoi/) (and currently qoixx is fastest one on x86_64 as far as I know). So, even if practical, implementing entropy coding on qoixx would be seemed excessive for me from what qoixx aims. Fortunately qoixx is the OSS under MIT, so you can implement the derivative program using qoixx as the qoi implementation. I find such efforts interesting, and when you find any suggestions for improvement of qoixx in your efforts, please report them here.

Yes, I understand. Thanks for your reply.
Unfortunately, I'm more of a Javascript guy myself, by need not by choice, and not a very Senior one at that. I can barely read your code if need be, but I wouldn't know where to start to implement it myself, sadly.
